name: Release on tag

on:
  push:
    tags:
      - v*

# Declare default permissions as read only.
permissions: read-all

jobs:
  release_github:
    name: GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get Flutter packages
        run: ./flutterw pub get

      - name: Remove build ID from native lib
        # cf https://github.com/deckerst/aves/issues/1521#issuecomment-5229015364
        run: |
          echo "PUB_CACHE=$PUB_CACHE"
          echo "Edit native lib build scripts from pub-cache hosted packages:"
          ls ${PUB_CACHE}/hosted/*
          sed -i -e 's/-Wl,/-Wl,--build-id=none,/' ${PUB_CACHE}/hosted/*/jni-*/src/CMakeLists.txt 2>/dev/null || true
        env:
          PUB_CACHE: $HOME/.pub-cache
