name: Release on tag

on:
  push:
    tags:
      - v*

# Declare default permissions as read only.
permissions: read-all

jobs:
  release_github:
    name: GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.47.2

      - name: Get Flutter packages
        run: flutter pub get

      - name: Remove build ID from native lib
        # cf https://github.com/deckerst/aves/issues/1521#issuecomment-5229015364
        run: |
          flutter doctor -v
          echo "pwd"
          pwd
          echo "ls"
          ls
          PUB_CACHE=.pub-cache
          echo "PUB_CACHE=$PUB_CACHE"
          ls ${PUB_CACHE}/hosted/*
          sed -i -e 's/-Wl,/-Wl,--build-id=none,/' ${PUB_CACHE}/hosted/*/jni-*/src/CMakeLists.txt 2>/dev/null || true
